my_FirstDBT:
  outputs:
    dev:
      account: uzcfxaq-ie47928
      database: NEW_DATABASE_test
      password: Vickygoraya78601
      role: accountadmin
      schema: New_schema_Test
      threads: 4
      type: snowflake
      user: waqaszulfiqar
      warehouse: data_wh
  target: dev

